# Generated by Django 6.0.5 on 2026-06-16 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_rename_tables'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
