# Generated by Django 6.0.5 on 2026-07-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.IntegerField(choices=[(0, 'User'), (1, 'Admin')], default=0),
        ),
    ]
