# Generated by Django 6.0.5 on 2026-06-25 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('away_name', models.CharField(max_length=50)),
                ('home_name', models.CharField(max_length=50)),
                ('total_innings', models.PositiveSmallIntegerField(default=3)),
                ('mode', models.CharField(choices=[('cpu_auto', 'CPU auto, you click'), ('click_all', 'Click every at-bat'), ('auto_play', 'Auto-play whole game')], max_length=20)),
                ('state', models.JSONField()),
                ('play_log', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('finished', 'Finished')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseball_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
