# Generated by Django 6.0.5 on 2026-06-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameParticipant',
            fields=[
                ('participant_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_sequence', models.IntegerField(default=1)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'game_participant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('lineup_id', models.AutoField(primary_key=True, serialize=False)),
                ('batting_order', models.IntegerField()),
            ],
            options={
                'db_table': 'lineup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MLBGame',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('home_score', models.IntegerField(default=0)),
                ('away_score', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'game',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MLBSchedule',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_date', models.DateField()),
                ('game_time', models.TimeField(blank=True, null=True)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='Scheduled', max_length=20)),
            ],
            options={
                'db_table': 'schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('position', models.CharField(blank=True, max_length=30, null=True)),
                ('jersey_number', models.IntegerField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('height_inches', models.IntegerField(blank=True, null=True)),
                ('weight_lbs', models.IntegerField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('bats', models.CharField(blank=True, max_length=1, null=True)),
                ('throws', models.CharField(blank=True, max_length=1, null=True)),
                ('team_abbrev', models.CharField(blank=True, max_length=10, null=True)),
                ('season', models.IntegerField(blank=True, null=True)),
                ('g', models.IntegerField(blank=True, null=True)),
                ('g_p', models.IntegerField(blank=True, null=True)),
                ('g_sp', models.IntegerField(blank=True, null=True)),
                ('g_rp', models.IntegerField(blank=True, null=True)),
                ('g_c', models.IntegerField(blank=True, null=True)),
                ('g_1b', models.IntegerField(blank=True, null=True)),
                ('g_2b', models.IntegerField(blank=True, null=True)),
                ('g_3b', models.IntegerField(blank=True, null=True)),
                ('g_ss', models.IntegerField(blank=True, null=True)),
                ('g_lf', models.IntegerField(blank=True, null=True)),
                ('g_cf', models.IntegerField(blank=True, null=True)),
                ('g_rf', models.IntegerField(blank=True, null=True)),
                ('g_of', models.IntegerField(blank=True, null=True)),
                ('g_dh', models.IntegerField(blank=True, null=True)),
                ('g_ph', models.IntegerField(blank=True, null=True)),
                ('g_pr', models.IntegerField(blank=True, null=True)),
                ('first_game', models.IntegerField(blank=True, null=True)),
                ('last_game', models.IntegerField(blank=True, null=True)),
                ('dataid', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='available', max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'player',
                'ordering': ['last_name', 'first_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('stadium_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(default='USA', max_length=50)),
                ('capacity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stadium',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('stat_id', models.AutoField(primary_key=True, serialize=False)),
                ('at_bats', models.IntegerField(default=0)),
                ('hits', models.IntegerField(default=0)),
                ('runs', models.IntegerField(default=0)),
                ('rbis', models.IntegerField(default=0)),
                ('doubles', models.IntegerField(default=0)),
                ('triples', models.IntegerField(default=0)),
                ('home_runs', models.IntegerField(default=0)),
                ('walks', models.IntegerField(default=0)),
                ('strikeouts', models.IntegerField(default=0)),
                ('stolen_bases', models.IntegerField(default=0)),
                ('innings_pitched', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('pitches_thrown', models.IntegerField(blank=True, null=True)),
                ('hits_allowed', models.IntegerField(default=0)),
                ('runs_allowed', models.IntegerField(default=0)),
                ('earned_runs', models.IntegerField(default=0)),
                ('walks_allowed', models.IntegerField(default=0)),
                ('ks_pitched', models.IntegerField(default=0)),
                ('home_runs_allowed', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'stats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(blank=True, max_length=5, null=True)),
                ('conference', models.CharField(blank=True, max_length=50, null=True)),
                ('division', models.CharField(blank=True, max_length=50, null=True)),
                ('head_coach', models.CharField(blank=True, max_length=50, null=True)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'team',
                'ordering': ['name'],
                'managed': False,
            },
        ),
    ]
