# Generated by Django 6.0.5 on 2026-06-25 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0002_gameparticipant_lineup_mlbgame_mlbschedule_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_games', to='baseball.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_games', to='baseball.team'),
        ),
    ]
