# Generated by Django 6.0.5 on 2026-06-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0003_game_away_team_game_home_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='away_roster',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='game',
            name='home_roster',
            field=models.JSONField(default=list),
        ),
    ]
