# Generated by Django 6.0.5 on 2026-06-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0004_game_away_roster_game_home_roster'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ab', models.SmallIntegerField(default=0)),
                ('singles', models.SmallIntegerField(default=0)),
                ('doubles', models.SmallIntegerField(default=0)),
                ('triples', models.SmallIntegerField(default=0)),
                ('home_runs', models.SmallIntegerField(default=0)),
                ('strikeouts', models.SmallIntegerField(default=0)),
                ('walks', models.SmallIntegerField(default=0)),
                ('sac_hits', models.SmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'game_stat',
                'managed': False,
            },
        ),
    ]
