# Generated by Django 6.0.5 on 2026-07-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0007_seed_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cpu_side',
            field=models.CharField(blank=True, choices=[('away', 'Away'), ('home', 'Home')], max_length=4, null=True),
        ),
    ]
