# Generated by Django 6.0.5 on 2026-07-20 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0008_game_cpu_side_alter_game_away_team_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='owner_side',
            field=models.CharField(blank=True, choices=[('away', 'Away'), ('home', 'Home')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baseball_games_as_player2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='mode',
            field=models.CharField(choices=[('cpu_auto', 'CPU auto, you click'), ('click_all', 'Click every at-bat'), ('auto_play', 'Auto-play whole game'), ('multiplayer', 'Multiplayer (invite a player)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('waiting', 'Waiting for player'), ('finished', 'Finished')], default='active', max_length=20),
        ),
    ]
