# Generated by Django 6.0.5 on 2026-07-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0013_rename_stats_to_player_career_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='streaky_per_game',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='streaky_per_inning',
            field=models.BooleanField(default=False),
        ),
    ]
