# Generated by Django 6.0.5 on 2026-08-18 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0019_game_bullpen_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='season_entry_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveSmallIntegerField(choices=[(8, '8 Teams'), (16, '16 Teams')])),
                ('player_roster', models.JSONField(default=list)),
                ('player_bullpen', models.JSONField(default=list)),
                ('team_ids', models.JSONField(default=list)),
                ('schedule', models.JSONField(default=list)),
                ('bracket', models.JSONField(default=list)),
                ('current_index', models.PositiveIntegerField(default=0)),
                ('stage', models.CharField(choices=[('regular', 'Regular Season'), ('playoffs', 'Playoffs'), ('finished', 'Finished')], default='regular', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseball_seasons', to=settings.AUTH_USER_MODEL)),
                ('player_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='baseball.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='season_games', to='baseball.season'),
        ),
    ]
